### ISSUE TITLE
Retrieving the light state

### ISSUE THREAD

**Issue by mainTAP** [timniklas/hass-govee_light_ble#8]
Hi,
Would it be possible to also retrieve the current status of the LED light, so that it reflects in Home Assistant when the physical button is used?
Thank you

**Comment by mainTAP** [comment]
Hi, thank you for looking into retrieving the state of the device.
I've tried this with h6181 LED strip, but it doesn't seem to be reading the state of the light.
When the strip is turned on/off via its own control panel, it doesn't reflect back to Home Assistant, and also when it's turned on/off from Home Assistant, but it fails to toggle the light, it also gets out of sync with what Home Assistant sees.

**Comment by timniklas** [comment]
The device status is loaded once when the integration is started, after which it is no longer updated.
Using the Govee app will probably lead to problems, currently I would only recommend using Home Assistant.

This is quite complex and will probably be added in a later release.

**Comment by mainTAP** [comment]
Thank you, just to add that I wasn't using the  Govee app, but the physical buttons on the LED strip.
I could refrain from using the physical button but as the strip is plugged into a monitor, it occasionally turns on/off when the monitor wakes up from sleep or on similar occasions.
It would be nice if it was possible to retrieve the on/off state periodically to keep the state updated in Home Assistant.

**Comment by timniklas** [comment]
I've got it working to retrieve the light parameters (power, brightness, color) via bluetooth.
Currently working on integrating it into home assistant.
![image](https://github.com/user-attachments/assets/e10e5e9c-aede-4106-83bc-c12fcf44c5f1)

**Comment by timniklas** [comment]
A preview is available in the pre release v2.5-pre3

**Comment by timniklas** [comment]
Implemented in Release 2.5
